name: fitness_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '2.10.4'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1
  intl: ^0.16.1
  cupertino_icons: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true

  assets:
  
    - lib/assets/images/unnamed.png
    - lib/assets/images/eaten.png
    - lib/assets/images/burned.png
    - lib/assets/images/dinner.png
    - lib/assets/images/lunch.png
    - lib/assets/images/snack.png
    - lib/assets/images/breakfast.png
    - lib/assets/images/bell.png
    - lib/assets/images/bottle.png
    - lib/assets/images/glass.png
    - lib/assets/images/back.png
    - lib/assets/images/runner.png
    - lib/assets/images/area1.png
    - lib/assets/images/area2.png
    - lib/assets/images/area3.png

    - lib/assets/images/tab_1.png
    - lib/assets/images/tab_1s.png
    - lib/assets/images/tab_2.png
    - lib/assets/images/tab_2s.png
    - lib/assets/images/tab_3.png
    - lib/assets/images/tab_3s.png
    - lib/assets/images/tab_4.png
    - lib/assets/images/tab_4s.png